'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicePersonas
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PersonaApp", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PersonaApp
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreField As String
        
        Private NacimientoField As Date
        
        Private EdadField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Nombre() As String
            Get
                Return Me.NombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreField, value) <> true) Then
                    Me.NombreField = value
                    Me.RaisePropertyChanged("Nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Nacimiento() As Date
            Get
                Return Me.NacimientoField
            End Get
            Set
                If (Me.NacimientoField.Equals(value) <> true) Then
                    Me.NacimientoField = value
                    Me.RaisePropertyChanged("Nacimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Edad() As Integer
            Get
                Return Me.EdadField
            End Get
            Set
                If (Me.EdadField.Equals(value) <> true) Then
                    Me.EdadField = value
                    Me.RaisePropertyChanged("Edad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Sexo() As String
            Get
                Return Me.SexoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SexoField, value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicePersonas.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Generating message contract since element name GetPersonaResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPersona", ReplyAction:="*")>  _
        Function GetPersona(ByVal request As ServicePersonas.GetPersonaRequest) As ServicePersonas.GetPersonaResponse
        
        'CODEGEN: Generating message contract since element name GetPersonasResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPersonas", ReplyAction:="*")>  _
        Function GetPersonas(ByVal request As ServicePersonas.GetPersonasRequest) As ServicePersonas.GetPersonasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeletePersona", ReplyAction:="*")>  _
        Sub DeletePersona(ByVal ID As Integer)
        
        'CODEGEN: Generating message contract since element name newPersona from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CreatePersona", ReplyAction:="*")>  _
        Function CreatePersona(ByVal request As ServicePersonas.CreatePersonaRequest) As ServicePersonas.CreatePersonaResponse
        
        'CODEGEN: Generating message contract since element name upPersona from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdatePersona", ReplyAction:="*")>  _
        Function UpdatePersona(ByVal request As ServicePersonas.UpdatePersonaRequest) As ServicePersonas.UpdatePersonaResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPersonaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPersona", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.GetPersonaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.GetPersonaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetPersonaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ID As Integer)
            MyBase.New
            Me.ID = ID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPersonaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.GetPersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.GetPersonaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetPersonaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPersonaResult As ServicePersonas.PersonaApp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPersonaResult As ServicePersonas.PersonaApp)
            MyBase.New
            Me.GetPersonaResult = GetPersonaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPersonasRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPersonas", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.GetPersonasRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.GetPersonasRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetPersonasRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPersonasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPersonasResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.GetPersonasResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.GetPersonasResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetPersonasResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPersonasResult() As ServicePersonas.PersonaApp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPersonasResult() As ServicePersonas.PersonaApp)
            MyBase.New
            Me.GetPersonasResult = GetPersonasResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CreatePersonaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CreatePersona", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.CreatePersonaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.CreatePersonaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CreatePersonaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public newPersona As ServicePersonas.PersonaApp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal newPersona As ServicePersonas.PersonaApp)
            MyBase.New
            Me.newPersona = newPersona
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CreatePersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CreatePersonaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.CreatePersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.CreatePersonaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class CreatePersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdatePersonaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdatePersona", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.UpdatePersonaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.UpdatePersonaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdatePersonaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public upPersona As ServicePersonas.PersonaApp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal upPersona As ServicePersonas.PersonaApp)
            MyBase.New
            Me.upPersona = upPersona
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdatePersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdatePersonaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicePersonas.UpdatePersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicePersonas.UpdatePersonaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class UpdatePersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits ServicePersonas.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicePersonas.ServiceSoap)
        Implements ServicePersonas.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicePersonas_ServiceSoap_GetPersona(ByVal request As ServicePersonas.GetPersonaRequest) As ServicePersonas.GetPersonaResponse Implements ServicePersonas.ServiceSoap.GetPersona
            Return MyBase.Channel.GetPersona(request)
        End Function
        
        Public Function GetPersona(ByVal ID As Integer) As ServicePersonas.PersonaApp
            Dim inValue As ServicePersonas.GetPersonaRequest = New ServicePersonas.GetPersonaRequest()
            inValue.Body = New ServicePersonas.GetPersonaRequestBody()
            inValue.Body.ID = ID
            Dim retVal As ServicePersonas.GetPersonaResponse = CType(Me,ServicePersonas.ServiceSoap).GetPersona(inValue)
            Return retVal.Body.GetPersonaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicePersonas_ServiceSoap_GetPersonas(ByVal request As ServicePersonas.GetPersonasRequest) As ServicePersonas.GetPersonasResponse Implements ServicePersonas.ServiceSoap.GetPersonas
            Return MyBase.Channel.GetPersonas(request)
        End Function
        
        Public Function GetPersonas() As ServicePersonas.PersonaApp()
            Dim inValue As ServicePersonas.GetPersonasRequest = New ServicePersonas.GetPersonasRequest()
            inValue.Body = New ServicePersonas.GetPersonasRequestBody()
            Dim retVal As ServicePersonas.GetPersonasResponse = CType(Me,ServicePersonas.ServiceSoap).GetPersonas(inValue)
            Return retVal.Body.GetPersonasResult
        End Function
        
        Public Sub DeletePersona(ByVal ID As Integer) Implements ServicePersonas.ServiceSoap.DeletePersona
            MyBase.Channel.DeletePersona(ID)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicePersonas_ServiceSoap_CreatePersona(ByVal request As ServicePersonas.CreatePersonaRequest) As ServicePersonas.CreatePersonaResponse Implements ServicePersonas.ServiceSoap.CreatePersona
            Return MyBase.Channel.CreatePersona(request)
        End Function
        
        Public Sub CreatePersona(ByVal newPersona As ServicePersonas.PersonaApp)
            Dim inValue As ServicePersonas.CreatePersonaRequest = New ServicePersonas.CreatePersonaRequest()
            inValue.Body = New ServicePersonas.CreatePersonaRequestBody()
            inValue.Body.newPersona = newPersona
            Dim retVal As ServicePersonas.CreatePersonaResponse = CType(Me,ServicePersonas.ServiceSoap).CreatePersona(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicePersonas_ServiceSoap_UpdatePersona(ByVal request As ServicePersonas.UpdatePersonaRequest) As ServicePersonas.UpdatePersonaResponse Implements ServicePersonas.ServiceSoap.UpdatePersona
            Return MyBase.Channel.UpdatePersona(request)
        End Function
        
        Public Sub UpdatePersona(ByVal upPersona As ServicePersonas.PersonaApp)
            Dim inValue As ServicePersonas.UpdatePersonaRequest = New ServicePersonas.UpdatePersonaRequest()
            inValue.Body = New ServicePersonas.UpdatePersonaRequestBody()
            inValue.Body.upPersona = upPersona
            Dim retVal As ServicePersonas.UpdatePersonaResponse = CType(Me,ServicePersonas.ServiceSoap).UpdatePersona(inValue)
        End Sub
    End Class
End Namespace
